server:
  port: 8091

spring:
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://rm-2zeedrx4ao895w03jko.mysql.rds.aliyuncs.com:3306/gd_subdb_1ehbei0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
   username: kaifa
   password: Goodo123



# thymeleaf configeration start
#spring:
  tymeleaf:
    model: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    cache: false
# thymeleaf configeration end
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.model
  configuration:
    map-underscore-to-camel-case: true
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
